apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5173
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-deployment
          image: lucasholter00/cv-client
          ports:
          - containerPort: 5173
