apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-deployment
        image: lucasholter00/cv-server
        ports:
        - containerPort: 8000

