name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9  # Specify the desired Python version
      - name: Install Dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirments.txt
      - name: Run Tests
        run: |
          cd server
          python manage.py test
